#!/usr/bin/env swift

// Script to extract accurate worker-building assignments from OperationalDataManager
// This will help us audit and fix incorrect assignments throughout the app

import Foundation

print("=== ACCURATE WORKER-BUILDING ASSIGNMENTS ===")
print("From OperationalDataManager.swift - Franco Management Operations")
print("")

// Kevin Dutan (38 tasks) - Highest volume worker
print("🔧 KEVIN DUTAN (38 tasks):")
print("   Buildings:")
print("   • 131 Perry Street (ID: 10) - 8 daily tasks")
print("   • 68 Perry Street (ID: 6) - 4 tasks (Sidewalk, Building Clean, Stairwell, Roof)")
print("   • 117 West 17th Street (ID: 9) - 2 tasks")
print("   • Rubin Museum (ID: 14) - 24 tasks (PRIMARY ASSIGNMENT)")
print("   • 112 West 18th Street (ID: 7) - Multiple tasks")
print("")

// Edwin Lema (18 tasks)
print("🧹 EDWIN LEMA (18 tasks):")
print("   Buildings:")
print("   • Stuyvesant Park (ID: 16) - Morning inspections")
print("   • 133 East 15th Street (ID: 15) - Boiler operations")
print("   • 117 West 17th Street (ID: 9) - Water filter maintenance")
print("   • Multiple mixed portfolio buildings")
print("")

// Luis Lopez (7 tasks)
print("🔨 LUIS LOPEZ (7 tasks):")
print("   Buildings:")
print("   • 41 Elizabeth Street (ID: 8) - PRIMARY (Bathrooms, Lobby, Elevator, Mail)")
print("   • 104 Franklin Street (ID: 4) - Sidewalk Hose")
print("   • 36 Walker Street (ID: 18) - Sidewalk Sweep")
print("   • Coverage worker for multiple locations")
print("")

// Mercedes Inamagua (7 tasks)
print("✨ MERCEDES INAMAGUA (7 tasks):")
print("   Buildings:")
print("   • CyntientOps HQ (ID: 20) - Evening shift")
print("   • Rubin Museum (ID: 14) - Roof Drain maintenance (2F Terrace)")
print("   • Simplified interface user")
print("")

// Greg Hutson (6 tasks)
print("🔧 GREG HUTSON (6 tasks):")
print("   Buildings:")
print("   • 12 West 18th Street (ID: 1) - Complete Service")
print("   • West Village properties (ID: 5, 6)")
print("   • Building specialist")
print("")

// Angel Guirachocha (5 tasks)
print("🗑️ ANGEL GUIRACHOCHA (5 tasks):")
print("   Buildings:")
print("   • 68 Perry Street (ID: 6) - DSNY Trash Bins")
print("   • 112 West 18th Street (ID: 7) - Night shift")
print("   • 138 West 17th Street (ID: 5) - Night/DSNY operations")
print("")

// Shawn Magloire (7 tasks) - Management
print("🎨 SHAWN MAGLOIRE (7 tasks - Management):")
print("   Buildings:")
print("   • Administrative oversight")
print("   • Cross-building management")
print("")

print("=== BUILDING ID REFERENCE ===")
print("1:  12 West 18th Street")
print("3:  135-139 West 17th Street")
print("4:  104 Franklin Street")
print("5:  138 West 17th Street")
print("6:  68 Perry Street")
print("7:  112 West 18th Street")
print("8:  41 Elizabeth Street")
print("9:  117 West 17th Street")
print("10: 131 Perry Street")
print("11: 123 1st Avenue")
print("13: 136 West 17th Street")
print("14: Rubin Museum")
print("15: 133 East 15th Street")
print("16: Stuyvesant Park")
print("17: 178 Spring Street")
print("18: 36 Walker Street")
print("20: CyntientOps HQ")
print("")

print("=== CRITICAL CORRECTIONS NEEDED ===")
print("❌ Luis Lopez is NEVER assigned to 68 Perry Street")
print("✅ Luis Lopez PRIMARY: 41 Elizabeth Street")
print("❌ Kevin Dutan is PRIMARY for Rubin Museum (24 tasks)")
print("✅ Mercedes roof drain task is at Rubin Museum, not elsewhere")
print("")