# .swiftlint.yml
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - force_unwrapping
  - empty_count
  - empty_string

force_unwrapping:
  severity: error

identifier_name:
  excluded:
    - id

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

file_length:
  warning: 1000
  error: 2000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500
